### ISSUE TITLE
See if remote FTP editing can be supported

### ISSUE THREAD

**Issue by keegnotrub** [keegnotrub/coda-sass-plugin#1]

**Comment by mattejames** [comment]
Late to the party here, I know, but I would absolutely love for this plugin to work with remote files as my development environment is actually in the cloud.

Just to make sure I understand the context, is the issue that partials may exist on the remote system and you're not sure what directory they're in?  Or is it that you have to traverse just the same directory as the .scss file, but that even this can take a bit of time?  If so, how much time?  IMHO, the trade-off might be worth it for those who work remotely like this.  I mean, if it's 30 seconds or so, that's a deal-breaker and not even worth pursuing.  But if you can get it to work over FTP and it takes 1-3 seconds to compile, that's a reasonable wait time from my perspective.

Just a thought for those who don't have Transmit.

**Comment by maxflex** [comment]
Really need this feature too.

**Comment by keegnotrub** [comment]
@mattejames - you're exactly right, the issue is that when partials exist the latency to traverse a remote file system and pull them down can sometimes be a few seconds long.

I compile the sass files on the main UI thread so this lag would cause Coda to freeze for a few seconds.  I could possibly look into doing the work on a separate thread and displaying a progress bar if it takes longer than a 1/2 second or something but right now thats more work than I can allot time for with this project.

Until I can find the time I would recommend mounting the remote file system as a local disk via Transmit or OS X Fuse (open source).

**Comment by GabrielGil** [comment]
I know I've been one of those who wanted this feature working ASAP, however nowadays based on my experience, I highly recommend to move somewhere else your dev environment.
Local environment is obsolete in the cloud era. **I'd def recommend use [Cloud9](http://c9.io)**.
Also for those looking for a WP plugin for compile sass, this is a good option BUT the compiler version is not updated and some features might be missing. Also note, things like comment blocks might mess your final code upside down.
[WP-SCSS](https://wordpress.org/plugins/wp-scss)

**Comment by mattejames** [comment]
I thought it would be worth documenting one issue I ran into.  If you plan to use Transmit to load up a remote SFTP share as a volume, know that the ownership of the files change when this occurs.  So if your files are owned by the SFTP user on the remote server and you load up the volume, they become owned by your local OS X user instead.  For me, this translated into issues using WordPress to do updates since WP needs permission to overwrite files and may not have them if you change the owner.  Unfortunately, the only solution to the issue is to 777 the files according to Panic support.
