### ISSUE TITLE
inline comments causing compiling issue

### ISSUE THREAD

**Issue by dypsilanti** [keegnotrub/coda-sass-plugin#23]
If I create an inline comment on a new line, after a comma, the scss won't compile and an error occurs. 

I've been using this plugin for the better part of a year across numerous scss files and this has suddenly started happening. Is this due to the most recent update?

![screen shot 2015-05-05 at 3 56 05 pm](https://cloud.githubusercontent.com/assets/5806663/7481700/ff2caf6a-f33f-11e4-8a1e-bf62bcbc2010.png)

**Comment by keegnotrub** [comment]
@dypsilanti - Thanks for letting me know.  This does look like a regression again the latest version of libsass (the library I use to compile the scss). I'll need to [submit an issue](https://github.com/sass/libsass/issues) with them.  When I get to it I'll reference this ticket, otherwise feel free to submit an issue with them as well.

In the meantime I believe you can work around by either dropping back a version or by using block level comments:

    .context-course_{
      // S15
      &3333, 
      // F15
      &4444 {
        .m0 { color :red };
      }
    }

**Comment by keegnotrub** [comment]
@dypsilanti I believe this is now addressed in the [latest release](https://github.com/keegnotrub/coda-sass-plugin/releases/tag/v3.1.1) from my testing.  Closing this issue for now but feel free to reopen if still is an issue for you.
