### ISSUE TITLE
Coda 2 does not recognize .css file change for publishing

### ISSUE THREAD

**Issue by FBRTMaka** [keegnotrub/coda-sass-plugin#4]
Hi,

I noticed that Coda 2 does not recognize when the css file generated has been updated after saving the scss file.  This makes it difficult when using the publish feature, as I can publish the scss file but have to manually file transfer my new generated css file.

Is there a setting?

Thanks!

**Comment by jodinathan** [comment]
Hi,

It is happening again.
Coda stopped checking for local changed files outside the editor.
:(

**Comment by Rayken** [comment]
Status?

**Comment by keegnotrub** [comment]
I'm trying to carve out some free time to test these.  Just to confirm, this issue was closed but it reappeared sometime after v2.5 correct?

Also, the following doesn't fix the problem right?

http://hicksdesign.co.uk/journal/detecting-compiled-css-changes-with-coda-2

**Comment by Rayken** [comment]
Don't know when. It's not a fix though it's a work-around and it requires
you to work with the publish feature - you can't simply connect to a remote
server, go to your CSS folder and make a style.scss and start coding
without a lot of tinkering..

**Comment by keegnotrub** [comment]
Thanks @Quaked - I believe then this issue might not be the correct one to re-open as it deals with publishing.  Perhaps #29 is more appropriate?  I'll close this issue for now but let me know if that isn't correct.

**Comment by mattyfew** [comment]
I've been having this problem with Coda for a while now. One instance it works fine, the next it does not. I've tried everything. What gives?

**Comment by Warkman** [comment]
Im using 2.6.1 and it has just stared with this problem. On some sites it recognises the changes and ques for publishing then on other sites it does not pick up the changes? What do to Coda?

**Comment by padcreative** [comment]
I have this problem as well. It's intermittent. Sometimes Coda recognises the file sometimes not. I think this might be a Coda issue rather than an issue with the plugin. Sometimes if I change an image with Photoshop it doesn't queue it for Publishing and sometimes it does.

Can always ctrl-click on the css file and publish manually but it's far better when queued!

**Comment by benique** [comment]
I have the same problem with Coda 2.6.10. I lost some files that way because I ussumed that all scss the files on the server were the newest ones. It's really annoying. I can't believe that this problem still exists after that many years. I restartet Coda and it is still not working. Please finally fix this.

**Comment by padcreative** [comment]
Just to update, my problem with the files not queuing for publishing is due to the time on the saved files being in the past when compared with the versions on the live server. This is because our local Mac server's clock sometimes runs slow. When I look at the Mac server via a shared screen, you can see the time is a few mins late. By virtue of sharing the screen, it tends to then bring the clock back to the right time. There is a way to keep the clock in sync, but I haven't bothered to sort it out yet. I know that when I save my SCSS files, the compiled CSS file will be updated so I can just manually publish it if it's not queuing.

I hope that helps other people in the same situation – ie. if you work off a Mac server rather than your own computer, this could well be the issue.
